### ISSUE TITLE
Submit our blog to R-Bloggers

### ISSUE THREAD

**Issue by DominikRafacz** [turtletopia/turtletopia.github.io#3]
We can easily submit our blog and boost number of people we reach to.

https://www.r-bloggers.com/add-your-blog/

> Please submit your blog only *after* you made sure that:
> 1) There is at least one high quality R post 
> 2) The feed you submit is ONLY  about R (e.g: with R code, or directly related to the R world/community).  
> 3) Your feed includes post written ONLY in English.
> 4) Your posts are "meaty" (i.e.: Short pieces of text are excluded from this feed)
> 5) The feed has the FULL content (i.e.: not abstract/excerpts)
> 6) Your feed loads properly on https://simplepie.org/demo/ (if it doesn't, try using http://feeds.feedburner.com/ and submit that feed instead)
> 7) You provided a link-back to [r-bloggers.com](http://r-bloggers.com/)

**Comment by ErdaradunGaztea** [comment]
Let's make it a checklist:

- [x] 1. There is at least one high quality R post
- [x] 2. The feed you submit is ONLY about R (e.g: with R code, or directly related to the R world/community).
- [x] 3. Your feed includes post written ONLY in English.
- [x] 4. Your posts are "meaty" (i.e.: Short pieces of text are excluded from this feed)
- [x] 5. The feed has the FULL content (i.e.: not abstract/excerpts)
- [x] 6. Your feed loads properly on https://simplepie.org/demo/ (if it doesn't, try using http://feeds.feedburner.com/ and submit that feed instead)
- [x] 7. You provided a link-back to [r-bloggers.com](http://r-bloggers.com/)

**Comment by DominikRafacz** [comment]
Submitted, now waiting for an acceptance
